### ISSUE TITLE
benchmark?

### ISSUE THREAD

**Issue by hooopo** [GrottoPress/mel#1]
Is there benchmark data for Mel? Compare with sidekiq or sidekiq.cr

**Comment by akadusei** [comment]
Not at the moment. I may add code for benchmarking, although I'm not really sure what to benchmark. I assume the bottleneck would be mostly IO (redis).

**Comment by hooopo** [comment]
![image](https://user-images.githubusercontent.com/63877/115115094-0d925680-9fc5-11eb-8468-6955459313d8.png)
https://github.com/mperham/sidekiq.cr/blob/master/bench/load.cr

I think Mel can do better with batch mode.

**Comment by akadusei** [comment]
Great! Will take a look.
